### PR TITLE
bug: fix favicon URL

### PR DESCRIPTION
**Pull request by carlinmack**
Favicon is in /img/ directory: https://github.com/ror-community/ror-site/blob/master/static/img/favicon.ico

### CODE REVIEW

**Comment by amandafrench** [comment]
Duplicate of ror-community/ror-roadmap#228

**Comment by carlinmack** [comment]
This is a pull request, not an issue

**Comment by carlinmack** [comment]
@amandafrench btw the commit you made still has an [issue](https://github.com/ror-community/ror-app/commit/2d021a89236519452175c623758ce460bdd20108#commitcomment-144902482) and merging this Pull Request would fix it

**Comment by amandafrench** [comment]
@carlinmack Yes! Sorry for delay. Let me see if we can fix the favicon without waiting on https://github.com/ror-community/ror-app/pull/219 -- that PR _also_ fixes the favicon among several other changes but is waiting to be merged and deployed until some content changes are made.

**Comment by lizkrznarich** [comment]
Hi @carlinmack , thanks for spotting this. The favicon is one of the assets that's shared between ror-app and ror-site, so `/img` is not actually located in the root of ror-app. There is a custom baseURL var configured as noted in the [readme](https://github.com/ror-community/ror-app?tab=readme-ov-file#note) which is used to point to shared assets. If can update your change to `href="{{content-for 'baseURL'}}/img/favicon.ico"`, I'll accept the PR.

**Comment by carlinmack** [comment]
@lizkrznarich Many apologies for the long delay, I have fixed this PR now

**Comment by lizkrznarich** [comment]
@carlinmack Thanks! All set and deployed to all envs now!

**Pull request merged**
